### ISSUE TITLE
Standardise printing of significant digits in results

### ISSUE THREAD

**Issue by smishr** [xKDR/Survey.jl#170]
There should be logical consistency in how many significant digits are printed or shown as the result. This maybe different to the actual evaluated result (which may have floating point issues).

Eg.
```Julia
julia> apisrs = load_data("apisrs");

julia> srs = SurveyDesign(apisrs; weights = :pw) |> bootweights

julia> tot = total(:api00, srs)
1×2 DataFrame
 Row │ total      SE
     │ Float64    Float64
─────┼────────────────────
   1 │ 4.06689e6  57644.8

julia> mn = mean(:api00, srs)
1×2 DataFrame
 Row │ mean     SE
     │ Float64  Float64
─────┼──────────────────
   1 │ 656.585  9.30656
```
Above, 656.585 is printed answer, but the actual evaluated value is 656.5849999999991.

In R
```R
> srs <- svydesign(data=apisrs, weights=~pw,fpc=~fpc)
> svytotal(~api00, srs)
        total    SE
api00 4066888 58241
```

What can be suitable strategy for consistent printing?

**Comment by iuliadmtru** [comment]
There is a way to configure your REPL using [IOContext](https://docs.julialang.org/en/v1/base/io-network/#Base.IOContext). The relevant option in our case is probably `:compact`, but that is already set to `true` by default. There is no option to choose whether to suppress scientific notation of not (at least I couldn't find one). See also [this discussion](https://github.com/JuliaLang/julia/issues/46267) or the [Julia documentation for prompt modes](https://docs.julialang.org/en/v1/stdlib/REPL/#The-different-prompt-modes). Maybe [printf](https://docs.julialang.org/en/v1/stdlib/Printf/) can also be used for this purpose, although I don't really see how. This is not exactly what you're saying, since this is something that the user must configure, not a standard that we can give.

However, I don't think we need this standard. Maybe there's a way to suppress scientific notation, but I don't think we should enforce this in our package. The user can configure this on their own, the way they prefer it. This is more a matter of taste.

**Comment by smishr** [comment]
okay. lets not worry too much about it for now.

**Comment by smishr** [comment]
I think by changing from `sigdigits` to `digits` in #172 it achieves the above.
