### ISSUE TITLE
Constructor to directly read replicate weights data

### ISSUE THREAD

**Issue by ayushpatnaikgit** [xKDR/Survey.jl#194]
Currently, you need a `SurveyDesign` to make a `ReplicateDesign`; however, you should be able to make it directly. For privacy reason, in many datasets, only the replicate weights are given and not the actual weights.

**Comment by smishr** [comment]
@codetalker7 can you have a look into this

**Comment by codetalker7** [comment]
> Currently, you need a `SurveyDesign` to make a `ReplicateDesign`; however, you should be able to make it directly. For privacy reason, in many datasets, only the replicate weights are given and not the actual weights.

Hi @smishr @ayushpatnaikgit I had a few questions about this.  For this discussion, suppose our input `DataFrame` is called `apistrat_with_replicates`, which we generate as follows.

```julia
using Survey, DataFrames, CSV
apistrat = load_data("apistrat")
dstrat = SurveyDesign(apistrat; strata=:stype, weights=:pw)
bootstrat = bootweights(dstrat; replicates=10)
CSV.write("input.csv", bootstrat.data)

# so our input will be
apistrat_with_replicates = CSV.read("intput.csv", DataFrame)

```

Like we discussed last time, the constructor could be something like: 

```julia
function ReplicateDesign(
        data::AbstractDataFrame;
        clusters::Union{Nothing,Symbol,Vector{Symbol}} = nothing,
        strata::Union{Nothing,Symbol} = nothing,
        popsize::Union{Nothing,Symbol} = nothing,
        weights::Union{Nothing,Symbol} = nothing,    # everything is the same till here,
        replicate_weights::Vector{Symbol}
)
```
So, the only thing we've added to the constructor is `replicate_weights` (a vector of `Symbol`s), which will point to the columns of `data` which contain the replicate weights (but as in point 2 below, I think we don't even need this argument).

Now, my question: 

1. The code for this constructor is pretty much the same as the constructor for `SurveyDesign` right, since we don't need to call `bootweights` to create the replicate weights? In the case when we're only given replicate weights and not the actual weights, the constructor still works out.

2. In the `ReplicateDesign` constructor, should we even have the `replicate_weights` argument? This is because we are not touching the columns in `replicate_weights` at all (in the constructor), and we're not storing these symbols as a property of the `ReplicateDesign` struct either.

**Comment by smishr** [comment]
You are correct that R constructors do lots of different processing. Right now the Julia package doesnt have a lot of those bells and whistles. I think we can have a look at what differences matter for current + planned roadmap, focusing on those aspects

**Comment by codetalker7** [comment]
Can we close this now?
