### ISSUE TITLE
Testing and Documenting - Domain estimation for `StatifiedSample`

### ISSUE THREAD

**Issue by smishr** [xKDR/Survey.jl#71]
Sarndal Survey Sampling talks about Domain estimation with stratas in and around example 10.3.3 pg 394 of the book. Estimator for domain means and their variance is given in the screenshot below.

<img width="768" alt="image" src="https://user-images.githubusercontent.com/43640926/199425738-c568bc76-c823-4b2a-b23c-625da2bed7fe.png">

**Comment by iuliadmtru** [comment]
Can you add a link to this resource?

**Comment by iuliadmtru** [comment]
Following the above formulas I tried to implement `svymean` and `sem_svyby` for `StratifiedSample`s. You can find the code in the [domain_estimation](https://github.com/iuliadmtru/Survey.jl/tree/domain_estimation) branch in my fork (specifically, [this commit](https://github.com/iuliadmtru/Survey.jl/commit/5f6c567f880f816efe9f36d93296d4091b3b0a42)).

To get here I went through multiple trials and failures, most notably while trying to use the new [metadata](https://dataframes.juliadata.org/latest/lib/metadata/) functionality for DataFrames. This was my thought process:

1. Since we sum over all strata, we can consider each stratum independently and do a sum over them in the end (eventually, I realised this is wrong). This means we need to group by strata, then group each stratum by domain. We combine these small domain+strata groups with the relevant statistic (in my case, `svymean`) according to the column specified by `formula`. Finally, we combine the three resulting data frames by summing `mean` column.

2. For each stratum group we need to know the stratum sample size and population size. We had that information inside the `StratifiedSample` design, but there was no way to pass it through `combine`. This is why I thought about metadata. Unfortunately, I couldn't find a way to pass the metadata through `combine` either. Since metadata doesn't support `GroupedDataFrame`s I assigned metadata for each `SubDataFrame` inside a group. But after passing the group to `combine` I realised there is no way to capture that information inside the function that I use with `combine`. Maybe there's a way to index the groups and find that information in some complicated way. Anyway, I gave up on metadata :(.

3. After some more thinking I realised we can add the sample size and population size vectors to the data frame inside the design, just like we did with `weights`. This was exactly the reason why we did this with `weights`, so we can pass them to `combine`. This takes up more space, but is definitely faster than any other way I could think of that essentially does what `combine` does, cause `combine` surely does it 1000 times better. I figured time efficiency is more important than space efficiency in this case. So I did that, and then I was able to provide all the necessary information to `svymean` and `sem_svyby` (I also added `fpc` to the design data frame).

4. I managed to get results, but they are wrong. Out of frustration I changed a lot of multiplications/divisions/random stuff around to see if I could get the correct results but I didn't succeed. This is why, finally, together with @smishr I realised point 1 was wrong.

@smishr Take a look and please share what you have as well. Maybe if we combine our solutions we can fix this.

**Comment by smishr** [comment]
Okay I attempted domain estimation and was able to get the mean calculation working for cases where each domain x strata exists. my latest code is in [this branch](https://github.com/smishr/Survey.jl/tree/domain_stratified_sample). I am having look at @iuliadmtru implementation and try to combine both approaches to get correct function.

**Comment by smishr** [comment]
OKay i have combined iulias idea for having popsize and sampsize *inside* the dataframe instead of a Vector outside the `data`. This way when we are combining things inside `groupby`, you can access nh and Nh by taking first. This is not the ideal but i think it will work

**Comment by smishr** [comment]
[This branch](https://github.com/smishr/Survey.jl/tree/domain_stratified_sample) fixed both iulias and my issue. Right now it retruns only the mean, not the variance. But it is working for all domains (even when a strata doesnt exist within a domain).

**Comment by smishr** [comment]
Hi @iuliadmtru I added the variance formula, now we get exactly the same results as R for `svyby(:api00,:cname,strat,svymean)`
<img width="456" alt="image" src="https://user-images.githubusercontent.com/43640926/201660662-648bdbd4-cc32-4fed-b36b-f4bb4c01eb59.png">

Please have a look the the branch. I think we can start testing it

**Comment by iuliadmtru** [comment]
This has been fixed with #84 and testing is covered in issues #103 and #104.
